### ISSUE TITLE
Add linting tool

### ISSUE THREAD

**Issue by codders** [advancedtelematic/sota_client_cpp#21]
Would like to add a linting tool to the project to check for quality issues. @embmk if you have a tool that you normally use, please let me know the details and I'll get it integrated

**Comment by embmk** [comment]
We are using pc-lint but it only runs on windows...
http://www.gimpel.com/html/pcl.htm

**Comment by codders** [comment]
K. We went with clang-format and clang-check, as that's what we're using in other projects. This is now merged.
