### ISSUE TITLE
File write callback for curl

### ISSUE THREAD

**Issue by embmk** [advancedtelematic/sota_client_cpp#37]
Until now a callback that writes server responses into a string is used. When issue #36 was considered, the curl-handle that is used for the actual download should be configured to use a callback that writes directly into a file. The callback should be more or less like the string callback but use a ofstream or something similar.
Note that the curl-operation that actually downloads the file has to be determined as there may be HTTP 30X redirects and this could lead to writing the redirect URL into a file when using the file-write-callback at the wrong place.

**Comment by cajun-rat** [comment]
Closing because this is an implementation detail
