### ISSUE TITLE
OTAC-SYS-2 Exit with meaningful error if required configuration is absent 

### ISSUE THREAD

**Issue by codders** [advancedtelematic/sota_client_cpp#4]
The client should quit with a useful error message if no config file is supplied

**Comment by embmk** [comment]
I do return with failure when the config file is missing as I don't want the program to continue without the configuration. This lets the tests fail now.
A possible fix would be to mark all testcases that don't use the example config file to succeed when the program exits with an error. But this will make the tests somehow meaningless.

**Comment by codders** [comment]
Can you not supply a config file in the test runner?

**Comment by embmk** [comment]
I can do that

**Comment by embmk** [comment]
Can I close merged/pulled issues?

**Comment by codders** [comment]
Sure. If the code for the issue has been reviewed / merged you can close the issue.
