### ISSUE TITLE
Switch configuration file format to toml

### ISSUE THREAD

**Issue by cajun-rat** [advancedtelematic/sota_client_cpp#45]
At the moment the configuration file format is yaml, but the configuration files generated by ATS Garage are in toml format.  We should make sota_client_cpp read these files directly.

As an implementation note, .toml is thing from the rust world, but it is very close to the Windows INI file format, which boost PropertyTree can read, although the " around strings need to be stripped by hand.

Acceptance Criteria:

- The ota-plus-sdk-<bla>.toml files generated by ATS Garage can be passed to sota_client --config

**Comment by patriotyk** [comment]
Should we drop yaml support? Or just auto detect format by extension, and support both?

**Comment by cajun-rat** [comment]
Just drop yaml support--we haven't shipped anything that uses yaml yet 

Cheers 

Phil

On 16 December 2016 22:56:11 CET, patriotyk <notifications@github.com> wrote:
>Should we drop yaml support? Or just auto detect format by extension,
>and support both?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/advancedtelematic/sota_client_cpp/issues/45#issuecomment-267705425

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jeremiah** [comment]
The great thing about standards is that there are so many! :-)
