### ISSUE TITLE
Add D-Bus gateway

### ISSUE THREAD

**Issue by taheris** [advancedtelematic/sota_client_cpp#48]
This should support the same operations that exist in the Rust implementation. Namely:

- publish the `UpdateAvailable`, `DownloadComplete` and `InstalledSoftwareNeeded` events to the `software_manager{,_path}` paths defined in the config.
- handle the `initiateDownload`, `abortDownload` and `updateReport` methods

A Franca IDL interface description of the methods can be found here: https://github.com/advancedtelematic/genivi_swm/blob/master/franca_idl/SotaClient.fidl.

The sd-bus library from systemd should be used. In addition, conditional compilation should be added such that the D-Bus gateway may be excluded (including the libraries) at compile time.

**Comment by patriotyk** [comment]
During the work on this issue, I have found one problem. sd-bus library uses some C extensions that is not supported by c++ compiler, as result it is not possible to compile our dbusgateway code. https://github.com/systemd/systemd/issues/4858  Even if we rewrite existent macroses to c++, I am not sure there is no another C-only code. Another solution might be to use GENIVIs c++ dbus api https://github.com/GENIVI/capicxx-dbus-tools/wiki/CommonAPI-C---D-Bus-in-10-minutes Also it includes tools that can generate nice c++ stub code from Franca IDL file.

**Comment by patriotyk** [comment]
GENIVI Common API requires c++11 ((

**Comment by cajun-rat** [comment]
I'm fine with requiring C++11 for the GENIVI integration.  'Old' (pre-C++11) systems will use a different method to install packages, so requiring C++11 in this part only will be fine
