### ISSUE TITLE
Establish HTTPS OAuth communication with server

### ISSUE THREAD

**Issue by codders** [advancedtelematic/sota_client_cpp#5]
Connect to configured server and retrieve Access Token

**Comment by embmk** [comment]
Is it possible to get a HTTP example for the process referring to Garage.
I would start with https://app.atsgarage.com/api/v1/mydevice/#stuff but maybe thats not the right place to look for it.
I tried to get curl running, but there seems to be an issue with the currently used ubuntu library...

**Comment by embmk** [comment]
I created a device in Garage and downloaded the toml file containing the information I should need, but a simple dry run delivers this:

curl -X POST -d "grant_type=client_credentials&;client_id=25ea34e0-074c-4bfb-94a1-d71e0c192d8a&;secret=CJH5gVipQ7" https://auth-plus.atsgarage.com/token
{
  "error" : "invalid_client"
}

**Comment by embmk** [comment]
I tried to get started with libcurlpp a C++ wrapper for libcurl, but unfortunately the version of the library in xenial and trusty is broken. So I will stick to libcurl instead.

[https://stackoverflow.com/questions/33420631/link-errors-with-curlpp](url)

**Comment by codders** [comment]
In your example curl POST, you have some extra semicolons at the start of the client_id and secret - try removing those.

**Comment by codders** [comment]
btw - would prefer if your comments don't paste account secrets directly :)

**Comment by embmk** [comment]
I thought about hiding a part too but decided that it might be fine because its just demo data.
So it is likely to be mistyping when using curl, not like I have to do something in ATS Garage to maybe make the device visible?

**Comment by codders** [comment]
It's demo data, but it's valid credentials to connect to our live system - would prefer to avoid DDoS attacks with valid keys :)

If you remove the semi-colons and get a good response from the token endpoint, you can then use the returned token to make an API request. At that point the device should appear online.

**Comment by embmk** [comment]
Is there a possiblity to delete the device in garage?
I did remove the semicolons and tried &amp instead of & but I always get an unknown client response. Therefore I was wondering if there is something I have to do on the garage site. I think I have a vague idea of what to do when I do get a token but that is the topic of another issue...
The thing that is left to do here is to get a positive response and to store the token.

**Comment by codders** [comment]
There's currently no way to delete devices in the garage. If you can send me the details of the CURL request by mail, I will investigate and let you know what the issue is.

**Comment by jerrytrieu** [comment]
@embmk You need to pass the client id and secret as Basic auth (not in the form body). 
We can revoke the client for that device, if when you create a new device.

**Comment by embmk** [comment]
I implemented a valid request to the server returning a token. The request is created using data from the config file. The response from the server is parsed using a simple regex for extracting the token, the tokens type and the expire "number".

**Comment by codders** [comment]
It's fine for a first iteration to use a regexp, but in generally we will want correct parsing of JSON values returned by the server. Please make sure you have a TODO and a ticket to add JSON parsing. Looks like the c jansson library might be a good bet, at least in terms of compliance: http://seriot.ch/parsing_json.php

**Comment by embmk** [comment]
I merged with the master to get lint analysis working but now it lacks clang-format. What do I have to do to get clang-format as i cannot find anything about it in the Readme?

**Comment by embmk** [comment]
I forgot to add curl to the travis/docker configuration. Will push an updated version when the first testcases are running.

**Comment by embmk** [comment]
Finally I found everything to get the build in docker and coverage working. The coverage increased a bit due to a new test target for testing the classes implemented for the OAuth2 token. There are parts of the code that are hard to cover due to usage of curl or other libraries. It is possible to "stub" curl, but this a lot of work.
BTW I'm afraid the build badge doesn't work for branches or it is only valid for the master.

**Comment by codders** [comment]
Yes - the build badge only applies to the master branch. Sounds like solid progress though - glad you've managed to make everything work. If you are working on a branch over multiple days, one nice practise is to make a pull request with a name starting [WIP] (for "work in progress"). It gives me a chance to see what you're working on and provide feedback, but I won't try and merge it or treat it as final until the [WIP] is removed.

**Comment by codders** [comment]
Why is this now assigned to me? Is there a pull request?

**Comment by embmk** [comment]
I was talking about putting it into Review, but I'll make pull request now instead.

**Comment by codders** [comment]
I can't review code that isn't in pull-request form, so anything you want me to look at should be a pull request. If you don't want me to merge it, just put [WIP] or [Do not merge] in the PR title.

**Comment by embmk** [comment]
I have created a cherry-picked branch due to messed up commit history. Shall I push it creating a new branch or is there a possibility to push it and overwrite this branch?

**Comment by codders** [comment]
You can force push to this branch. Just `git push -f origin feat/blah` from your cherry-picked version.

**Comment by codders** [comment]
This is now merged, but it would be great if you can add to the README some instructions on running the client with OAuth credentials.

**Comment by embmk** [comment]
Do I update the Readme using the following branch (issue 6)? It would at least be related to the scope of this issue.

**Comment by codders** [comment]
Sure. That will be fine.
