### ISSUE TITLE
Make simple API request using token

### ISSUE THREAD

**Issue by codders** [advancedtelematic/sota_client_cpp#6]
Use the previously retrieved (or cached token) to make an API request

**Comment by embmk** [comment]
Following these examples https://advancedtelematic.github.io/rvi_sota_server/swagger/sota-core.html#!/default/get_packages I try to figure out what URL I have to use exactly.
Is it maybe auth-plus.atsgarage.com/api/v1/... or app.atsgarage.com/api/v1.
Please tell me the URL where I reach the server API and maybe something about the fields I have to use making the HTTP request.

**Comment by jerrytrieu** [comment]
The server the client talks to is: https://sota-core.atsgarage.com/api/v1

You should see this in the 'toml' file that you download from the device page on the UI.

**Comment by codders** [comment]
There is also a complete reference implementation of the client available here:

https://github.com/advancedtelematic/rvi_sota_client

It's in Rust, but it's quite readable. You might consider compiling / running it (or downloading the pre-built version). If you run it with RUST_LOG=debug exported, you should see the interactions with the server.

**Comment by embmk** [comment]
@jerrytrieu I tried a request to the server using a freshly received token for getting "/mydevice/{uuid}/updates" and got this error:
"The supplied authentication is not authorized to access this resource."
Can you tell if I applied the token successfully but am maybe missing an update list on the server or something like that?
@codders It seems like I have to get docker to build the rust client, even for building the deb when downloading the repository as a zip file. I am not shure if this was is faster than asking questions here...

**Comment by jerrytrieu** [comment]
@embmk You need to pass the token as bearer in the Authorization header: "Bearer <token-value"

You can look at the `src/sota.rs` in rvi_sota_client to see the API it is using. The types are in the `src/datatypes` dir.

**Comment by embmk** [comment]
Thanks for your help, I managed to make an API request and got "[ ]" as response which should be fine for now.

**Comment by codders** [comment]
@codders - You should be able to download a pre-built version from the ATS Garage website. When you create a new device, it will give you the option to download the .deb OTA Client as either a 32 or 64 bit package for Intel.

**Comment by embmk** [comment]
I'd like to create pull request but I think I should merge with the master first. When I try to merge with the master the branches commit history "explodes" putting tons of commit ahead of the few I made. How can I avoid that?

**Comment by jerrytrieu** [comment]
@embmk You should not merge with master. You checkout master, make there are no changes, pull latest remote/master. Then checkout your branch and rebase on master, skipping any commits that are duplicates. Which branch are you trying to update? I will try and see.

**Comment by embmk** [comment]
@jerrytrieu I'm trying to get feat/6/api-request ready for a pull request. I forgot that it is possible to do a "cross branch rebase" as I did so many interactive rebases last week...

**Comment by jerrytrieu** [comment]
@embmk there are a lot conflicting commits between your branch and master. I suggest you squash the commits with the changes you want to merge, create a new branch off the latest master, and manually apply your change on the new branch.

**Comment by embmk** [comment]
@jerrytrieu I forced a push and rebasing with the master gives me Current branch .. is up to date... so it seems that everything is fine now

**Comment by embmk** [comment]
@jerrytrieu  looking at the branches commit history it isn't looking any better allthough I created a new branch and did only 2 commits. Is github showing me commits from the master and if it does how do I distinguish?

**Comment by jerrytrieu** [comment]
@embmk it looks okay now. It shows that you are two commits ahead of master. If you use a tool such as `tig` you will see the branches marked in the log.
